name: 'upload-indus-appstore'
description: 'Upload AAB file to Indus Appstore'
author: 'Yogesh Choudhary Paliyal'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'truck'
  color: 'green'

# Define your inputs here.
inputs:
  type:
    description: 'Action type UPLOAD_AAB | UPLOAD_APK | UPLOAD_APKs | UPDATE_METADATA | GET_APP_STATS | GET_APP_DETAILS | GET_APP_VERSIONS'
    required: true
    default: '1000'
  apiKey:
    description: 'Indus App Store API Key'
    required: true
    default: '1000'
  packageName:
    description: 'App Package Name'
    required: true
    default: ''
  aabFile:
    description: 'AAB File path'
    required: false
    default: '1000'
  signingKeyBase64:
    description: 'Key Store File Base 64'
    required: false
    default: ''
  keyPassword:
    description: 'Key Password'
    required: false
    default: ''
  keystoreAlias:
    description: 'Keystore Alias'
    required: false
    default: ''
  keystorePassword:
    description: 'Keystore Alias Password'
    required: false
    default: ''

outputs:
  result:
    description: 'Result of the job'

runs:
  using: node20
  main: dist/index.js
